CREATE TYPE "public"."date_confidence" AS ENUM('strong', 'verify', 'unknown');--> statement-breakpoint
CREATE TYPE "public"."housing_type" AS ENUM('entire', 'shared', 'unknown');--> statement-breakpoint
CREATE TYPE "public"."lead_status" AS ENUM('active', 'trashed');--> statement-breakpoint
CREATE TYPE "public"."agent_link_status" AS ENUM('pending', 'approved', 'denied', 'expired', 'consumed');--> statement-breakpoint
CREATE TYPE "public"."membership_role" AS ENUM('owner', 'editor', 'viewer');--> statement-breakpoint
CREATE TYPE "public"."project_status" AS ENUM('active', 'trashed');--> statement-breakpoint
CREATE TYPE "public"."search_run_status" AS ENUM('queued', 'claimed', 'running', 'completed', 'failed', 'cancelled');--> statement-breakpoint
CREATE TYPE "public"."source_review_status" AS ENUM('open', 'resolved');--> statement-breakpoint
CREATE TABLE "agent_links" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"device_code_digest" varchar(64) NOT NULL,
	"user_code" varchar(8) NOT NULL,
	"agent_label" varchar(120) NOT NULL,
	"environment_note" varchar(200) DEFAULT '' NOT NULL,
	"requested_cadence_minutes" integer,
	"status" "agent_link_status" DEFAULT 'pending' NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"interval_seconds" integer DEFAULT 5 NOT NULL,
	"poll_count" integer DEFAULT 0 NOT NULL,
	"last_polled_at" timestamp with time zone,
	"approved_by_id" bigint,
	"issued_token_id" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "agent_tokens" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" bigint NOT NULL,
	"name" varchar(120) NOT NULL,
	"token_prefix" varchar(16) NOT NULL,
	"digest" varchar(64) NOT NULL,
	"scopes" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"project_ids" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"expected_cadence_minutes" integer,
	"environment_note" varchar(200) DEFAULT '' NOT NULL,
	"exposed_to_chat" boolean DEFAULT false NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"revoked_at" timestamp with time zone,
	"last_used_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "audit_events" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"project_id" uuid,
	"action" varchar(120) NOT NULL,
	"object_type" varchar(80) NOT NULL,
	"object_id" varchar(100) DEFAULT '' NOT NULL,
	"actor_kind" varchar(24) NOT NULL,
	"actor_id" bigint,
	"token_id" uuid,
	"request_id" varchar(80) DEFAULT '' NOT NULL,
	"summary" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "auth_throttles" (
	"key_digest" varchar(64) PRIMARY KEY NOT NULL,
	"failure_count" integer DEFAULT 0 NOT NULL,
	"window_started_at" timestamp with time zone NOT NULL,
	"blocked_until" timestamp with time zone,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "idempotency_keys" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"user_id" bigint NOT NULL,
	"token_id" uuid,
	"endpoint" varchar(220) NOT NULL,
	"key" varchar(200) NOT NULL,
	"request_hash" varchar(64) NOT NULL,
	"response_status" integer,
	"response_body" jsonb,
	"expires_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "lead_comments" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "lead_comments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"lead_id" uuid NOT NULL,
	"author_id" bigint NOT NULL,
	"parent_id" bigint,
	"body" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"edited_at" timestamp with time zone,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "lead_interests" (
	"lead_id" uuid NOT NULL,
	"user_id" bigint NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "lead_interests_lead_id_user_id_pk" PRIMARY KEY("lead_id","user_id")
);
--> statement-breakpoint
CREATE TABLE "leads" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"project_id" uuid NOT NULL,
	"source" varchar(160) NOT NULL,
	"source_listing_id" varchar(200) DEFAULT '' NOT NULL,
	"canonical_url" varchar(2000) NOT NULL,
	"identity_hash" varchar(64) DEFAULT '' NOT NULL,
	"source_url" varchar(2000) DEFAULT '' NOT NULL,
	"title" varchar(500) NOT NULL,
	"summary" text DEFAULT '' NOT NULL,
	"location" varchar(500) DEFAULT '' NOT NULL,
	"price_display" varchar(120) DEFAULT '' NOT NULL,
	"price_amount" numeric(10, 2),
	"price_currency" varchar(3) DEFAULT 'USD' NOT NULL,
	"availability" varchar(500) DEFAULT '' NOT NULL,
	"housing_type" "housing_type" DEFAULT 'unknown' NOT NULL,
	"date_confidence" date_confidence DEFAULT 'unknown' NOT NULL,
	"park_notes" varchar(1000) DEFAULT '' NOT NULL,
	"attributes" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"verification_notes" text DEFAULT '' NOT NULL,
	"status" "lead_status" DEFAULT 'active' NOT NULL,
	"trashed_by_id" bigint,
	"trashed_at" timestamp with time zone,
	"creator_id" bigint NOT NULL,
	"revision" integer DEFAULT 1 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "leads_revision_positive" CHECK ("leads"."revision" >= 1)
);
--> statement-breakpoint
CREATE TABLE "profiles" (
	"user_id" bigint PRIMARY KEY NOT NULL,
	"display_name" varchar(120) NOT NULL,
	"timezone" varchar(64) DEFAULT 'UTC' NOT NULL,
	"bio" text DEFAULT '' NOT NULL,
	"personal_details" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"agent_paused_until" timestamp with time zone,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "project_changes" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"project_id" uuid NOT NULL,
	"sequence" bigint NOT NULL,
	"event_type" varchar(80) NOT NULL,
	"object_type" varchar(80) NOT NULL,
	"object_id" varchar(100) DEFAULT '' NOT NULL,
	"payload" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"tombstone" boolean DEFAULT false NOT NULL,
	"actor_id" bigint,
	"actor_kind" varchar(24) DEFAULT 'user' NOT NULL,
	"token_id" uuid,
	"occurred_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "project_invitations" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"project_id" uuid NOT NULL,
	"email" varchar(254) NOT NULL,
	"role" "membership_role" DEFAULT 'viewer' NOT NULL,
	"inviter_id" bigint NOT NULL,
	"token_digest" varchar(64) NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"accepted_at" timestamp with time zone,
	"revoked_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "project_memberships" (
	"project_id" uuid NOT NULL,
	"user_id" bigint NOT NULL,
	"role" "membership_role" NOT NULL,
	"joined_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "project_memberships_project_id_user_id_pk" PRIMARY KEY("project_id","user_id")
);
--> statement-breakpoint
CREATE TABLE "projects" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" varchar(200) NOT NULL,
	"slug" varchar(220) NOT NULL,
	"description" text DEFAULT '' NOT NULL,
	"current_prompt" text DEFAULT '' NOT NULL,
	"criteria" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"status" "project_status" DEFAULT 'active' NOT NULL,
	"creator_id" bigint NOT NULL,
	"prompt_revision" integer DEFAULT 0 NOT NULL,
	"latest_change_sequence" bigint DEFAULT 0 NOT NULL,
	"feed_epoch" varchar(64) NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "prompt_revisions" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"project_id" uuid NOT NULL,
	"revision" integer NOT NULL,
	"prompt" text NOT NULL,
	"criteria" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"editor_id" bigint,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "search_runs" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"project_id" uuid NOT NULL,
	"user_id" bigint NOT NULL,
	"token_id" uuid,
	"agent_label" varchar(120) NOT NULL,
	"prompt_revision" integer NOT NULL,
	"prompt_snapshot" text NOT NULL,
	"criteria_snapshot" jsonb NOT NULL,
	"status" "search_run_status" DEFAULT 'queued' NOT NULL,
	"lease_owner" varchar(120) DEFAULT '' NOT NULL,
	"lease_expires_at" timestamp with time zone,
	"claim_token_digest" varchar(64) DEFAULT '' NOT NULL,
	"attempt_count" integer DEFAULT 0 NOT NULL,
	"input_cursor" varchar(2000) DEFAULT '' NOT NULL,
	"output_cursor" varchar(2000) DEFAULT '' NOT NULL,
	"continuation" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"result_counts" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"summary" varchar(1000) DEFAULT '' NOT NULL,
	"idempotency_key" varchar(200) DEFAULT '' NOT NULL,
	"completed_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "sessions" (
	"digest" varchar(64) PRIMARY KEY NOT NULL,
	"user_id" bigint,
	"csrf_digest" varchar(64) NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"last_seen_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "source_plan_reviews" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"project_id" uuid NOT NULL,
	"user_id" bigint NOT NULL,
	"reported_by_token_id" uuid,
	"status" "source_review_status" DEFAULT 'open' NOT NULL,
	"observed_prompt_revision" integer NOT NULL,
	"resolved_prompt_revision" integer,
	"opened_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_reported_at" timestamp with time zone DEFAULT now() NOT NULL,
	"resolved_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"email" varchar(254) NOT NULL,
	"password_hash" text NOT NULL,
	"password_reset_required" boolean DEFAULT false NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "agent_links" ADD CONSTRAINT "agent_links_approved_by_id_users_id_fk" FOREIGN KEY ("approved_by_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "agent_links" ADD CONSTRAINT "agent_links_issued_token_id_agent_tokens_id_fk" FOREIGN KEY ("issued_token_id") REFERENCES "public"."agent_tokens"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "agent_tokens" ADD CONSTRAINT "agent_tokens_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "audit_events" ADD CONSTRAINT "audit_events_project_id_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."projects"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "audit_events" ADD CONSTRAINT "audit_events_actor_id_users_id_fk" FOREIGN KEY ("actor_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "audit_events" ADD CONSTRAINT "audit_events_token_id_agent_tokens_id_fk" FOREIGN KEY ("token_id") REFERENCES "public"."agent_tokens"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "idempotency_keys" ADD CONSTRAINT "idempotency_keys_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "idempotency_keys" ADD CONSTRAINT "idempotency_keys_token_id_agent_tokens_id_fk" FOREIGN KEY ("token_id") REFERENCES "public"."agent_tokens"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "lead_comments" ADD CONSTRAINT "lead_comments_lead_id_leads_id_fk" FOREIGN KEY ("lead_id") REFERENCES "public"."leads"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "lead_comments" ADD CONSTRAINT "lead_comments_author_id_users_id_fk" FOREIGN KEY ("author_id") REFERENCES "public"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "lead_interests" ADD CONSTRAINT "lead_interests_lead_id_leads_id_fk" FOREIGN KEY ("lead_id") REFERENCES "public"."leads"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "lead_interests" ADD CONSTRAINT "lead_interests_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "leads" ADD CONSTRAINT "leads_project_id_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."projects"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "leads" ADD CONSTRAINT "leads_trashed_by_id_users_id_fk" FOREIGN KEY ("trashed_by_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "leads" ADD CONSTRAINT "leads_creator_id_users_id_fk" FOREIGN KEY ("creator_id") REFERENCES "public"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "profiles" ADD CONSTRAINT "profiles_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "project_changes" ADD CONSTRAINT "project_changes_project_id_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."projects"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "project_changes" ADD CONSTRAINT "project_changes_actor_id_users_id_fk" FOREIGN KEY ("actor_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "project_changes" ADD CONSTRAINT "project_changes_token_id_agent_tokens_id_fk" FOREIGN KEY ("token_id") REFERENCES "public"."agent_tokens"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "project_invitations" ADD CONSTRAINT "project_invitations_project_id_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."projects"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "project_invitations" ADD CONSTRAINT "project_invitations_inviter_id_users_id_fk" FOREIGN KEY ("inviter_id") REFERENCES "public"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "project_memberships" ADD CONSTRAINT "project_memberships_project_id_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."projects"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "project_memberships" ADD CONSTRAINT "project_memberships_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "projects" ADD CONSTRAINT "projects_creator_id_users_id_fk" FOREIGN KEY ("creator_id") REFERENCES "public"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "prompt_revisions" ADD CONSTRAINT "prompt_revisions_project_id_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."projects"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "prompt_revisions" ADD CONSTRAINT "prompt_revisions_editor_id_users_id_fk" FOREIGN KEY ("editor_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "search_runs" ADD CONSTRAINT "search_runs_project_id_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."projects"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "search_runs" ADD CONSTRAINT "search_runs_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "search_runs" ADD CONSTRAINT "search_runs_token_id_agent_tokens_id_fk" FOREIGN KEY ("token_id") REFERENCES "public"."agent_tokens"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "source_plan_reviews" ADD CONSTRAINT "source_plan_reviews_project_id_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."projects"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "source_plan_reviews" ADD CONSTRAINT "source_plan_reviews_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "source_plan_reviews" ADD CONSTRAINT "source_plan_reviews_reported_by_token_id_agent_tokens_id_fk" FOREIGN KEY ("reported_by_token_id") REFERENCES "public"."agent_tokens"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "agent_links_device_digest_uniq" ON "agent_links" USING btree ("device_code_digest");--> statement-breakpoint
CREATE INDEX "agent_links_code_status_idx" ON "agent_links" USING btree ("user_code","status","expires_at");--> statement-breakpoint
CREATE UNIQUE INDEX "agent_tokens_digest_uniq" ON "agent_tokens" USING btree ("digest");--> statement-breakpoint
CREATE UNIQUE INDEX "idempotency_principal_endpoint_key_uniq" ON "idempotency_keys" USING btree ("user_id","token_id","endpoint","key");--> statement-breakpoint
CREATE INDEX "idempotency_expiry_idx" ON "idempotency_keys" USING btree ("expires_at");--> statement-breakpoint
CREATE UNIQUE INDEX "leads_source_identity_uniq" ON "leads" USING btree ("project_id","source","source_listing_id") WHERE "leads"."source_listing_id" <> '';--> statement-breakpoint
CREATE UNIQUE INDEX "leads_url_identity_uniq" ON "leads" USING btree ("project_id","identity_hash") WHERE "leads"."identity_hash" <> '';--> statement-breakpoint
CREATE INDEX "leads_project_status_updated_idx" ON "leads" USING btree ("project_id","status","updated_at");--> statement-breakpoint
CREATE UNIQUE INDEX "project_changes_sequence_uniq" ON "project_changes" USING btree ("project_id","sequence");--> statement-breakpoint
CREATE UNIQUE INDEX "project_invitations_token_uniq" ON "project_invitations" USING btree ("token_digest");--> statement-breakpoint
CREATE UNIQUE INDEX "projects_slug_uniq" ON "projects" USING btree ("slug");--> statement-breakpoint
CREATE UNIQUE INDEX "prompt_revisions_project_revision_uniq" ON "prompt_revisions" USING btree ("project_id","revision");--> statement-breakpoint
CREATE UNIQUE INDEX "search_runs_idempotency_uniq" ON "search_runs" USING btree ("project_id","user_id","idempotency_key") WHERE "search_runs"."idempotency_key" <> '';--> statement-breakpoint
CREATE INDEX "search_runs_active_idx" ON "search_runs" USING btree ("project_id","status","lease_expires_at");--> statement-breakpoint
CREATE INDEX "sessions_expiry_idx" ON "sessions" USING btree ("expires_at");--> statement-breakpoint
CREATE UNIQUE INDEX "source_plan_reviews_open_uniq" ON "source_plan_reviews" USING btree ("project_id","user_id") WHERE "source_plan_reviews"."status" = 'open';--> statement-breakpoint
CREATE UNIQUE INDEX "users_email_ci_uniq" ON "users" USING btree (lower("email"));