CREATE TABLE "saved_prompts" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "saved_prompts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" bigint NOT NULL,
	"title" varchar(200) NOT NULL,
	"prompt" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "audit_events" ALTER COLUMN "request_id" SET DATA TYPE varchar(100);--> statement-breakpoint
ALTER TABLE "audit_events" ALTER COLUMN "request_id" SET DEFAULT '';--> statement-breakpoint
ALTER TABLE "search_runs" ALTER COLUMN "agent_label" SET DATA TYPE varchar(160);--> statement-breakpoint
ALTER TABLE "search_runs" ALTER COLUMN "summary" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "search_runs" ALTER COLUMN "summary" SET DEFAULT '';--> statement-breakpoint
ALTER TABLE "search_runs" ADD COLUMN "started_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "source_plan_reviews" ADD COLUMN "resolved_by_token_id" uuid;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "last_login" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "legacy_is_staff" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "legacy_is_superuser" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "saved_prompts" ADD CONSTRAINT "saved_prompts_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "saved_prompts_user_title_uniq" ON "saved_prompts" USING btree ("user_id","title");--> statement-breakpoint
ALTER TABLE "source_plan_reviews" ADD CONSTRAINT "source_plan_reviews_resolved_by_token_id_agent_tokens_id_fk" FOREIGN KEY ("resolved_by_token_id") REFERENCES "public"."agent_tokens"("id") ON DELETE set null ON UPDATE no action;